# Generated by Django 4.0.6 on 2022-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0002_alter_menproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='menproduct',
            name='pictures',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/'),
        ),
    ]
