# Generated by Django 4.0.6 on 2022-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0003_remove_menproduct_image_menproduct_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='menproduct',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='paragraph',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
